### ISSUE TITLE
Resource Monitor stops responding on startup

### ISSUE THREAD

**Issue by ShadowTechXTS** [AluminiumTech/Specs-Boss#5]
I downloaded the Insider Preview 2017.0 Preview 3 but it crashed at startup.

**Comment by AluminiumTech** [comment]
This an issue with the check for update. Preview 4 will fix this.

**Comment by AluminiumTech** [comment]
This bug is fixed in Preview 4.

[Preview 4](https://github.com/AluminiumTech/Specs-Boss/releases/tag/2017.0-pre4)
