### ISSUE TITLE
3GB VRAM on a 4GB card... again

### ISSUE THREAD

**Issue by ShadowTechXTS** [AluminiumTech/Specs-Boss#7]
![capture](https://cloud.githubusercontent.com/assets/21186660/19947334/95cad0e4-a115-11e6-8ae2-62f462ebe5f9.PNG)

**Comment by AluminiumTech** [comment]
I will investigate this further......

**Comment by AluminiumTech** [comment]
@ShadowTechXTS I thought I was going to fix this but I have since decided to just re-write the Specs Boss app in Java and thus this issue will be fixed with that new app.

Sorry for any inconveniences or issues in the mean time.
