### ISSUE TITLE
Changing colors only effects the settings menu

### ISSUE THREAD

**Issue by ShadowTechXTS** [AluminiumTech/Specs-Boss#8]
I've tried restarting specs boss and everything.
![capture](https://cloud.githubusercontent.com/assets/21186660/19947390/dcbfc798-a115-11e6-84ca-c706b285c86f.PNG)

**Comment by AluminiumTech** [comment]
This will be fixed in Beta 1.5

**Comment by AluminiumTech** [comment]
@ShadowTechXTS I thought I was going to fix this but I have since decided to just re-write the Specs Boss app in Java and thus this issue will be fixed with that new app.

Sorry for any inconveniences or issues in the mean time.
